craigslist/urls.py
from django.urls import path
from craigslist.views import home, new_search

app_name = 'craigslist'

urlpatterns = [
    path('', home, name='home'),
    path('new_search/', new_search, name='new_search'),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('craigslist.urls', namespace='craig')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

craigslist/models.py
from django.db import models


class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}'.format(self.search)

    class Meta:
        verbose_name_plural = 'Searches'

craigslist/views.py
import requests
from bs4 import BeautifulSoup as bs4
from django.shortcuts import render
from requests.compat import quote_plus
from craigslist.models import Search

ROOT_URL = 'https://cosprings.craigslist.org'
BASE_SEARCH_URL = 'https://cosprings.craigslist.org/search/?query={}&sort=rel'
BASE_IMAGE_URL = 'https://images.craigslist.org/{}_300x300.jpg'


def home(request):
    url = 'https://cosprings.craigslist.org/'
    res = requests.get(url)
    res.raise_for_status()
    soup = bs4(res.text, "html.parser")

    linkList = []
    links = soup.select('#center a')
    for link in links:
        link_href = ROOT_URL + link.get('href')
        names = link.find('span').text
        linkList.append((link_href, names))

    firstHalf = linkList[:38]
    secondHalf = linkList[94:]
    newlinkList = firstHalf + secondHalf

    context = {
        'links': newlinkList,
    }

    return render(request, 'base.html', context)


def new_search(request):
    search = request.POST.get('search')
    Search.objects.create(search=search)
    final_url = BASE_SEARCH_URL.format(quote_plus(search))
    response = requests.get(final_url)
    data = response.text
    soup = bs4(data, "html.parser")

    post_listings = soup.find_all('li', {'class': 'result-row'})

    final_postings = []
    for i in post_listings:
        post_title = i.find(class_='result-title').text
        post_url = i.find('a').get('href')

        if i.find(class_='result-price'):
            post_price = i.find(class_='result-price').text
        else:
            post_price = 'N/A'

        if i.find(class_='result-image').get('data-ids'):
            post_image_id = i.find(
                class_='result-image').get('data-ids').split(',')[0].split(':')[1]
            post_image_url = BASE_IMAGE_URL.format(post_image_id)
        else:
            post_image_url = 'https://craigslist.org/images/peace.jpg'

        final_postings.append(
            (post_title, post_url, post_price, post_image_url))

    context = {
        'search': search,
        'final_postings': final_postings
    }
    return render(request, 'craigslist/new_search.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% include "head.html" %}

  <body>
    {% include "nav.html"%}

    <main role="main">
      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">Craigslist Scapper</h1>
          <p>
            This app has webscrap craigslist for easy nav.
          </p>
          <p>
            <a
              class="btn btn-primary btn-lg"
              href="https://cosprings.craigslist.org/"
              role="button"
              >Original Page &raquo;</a
            >
          </p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <!-- line 38 {{url craig:category}} -->
        <div class="row">
          {% for link in links %}
          <div class="col-md-4">
            <h2>{{link.1}}</h2>
            <p></p>
            <p>
              <a
                class="btn btn-primary"
                href="{{link.0}}"
                role="button"
                target="_blank"
                >View details &raquo;</a
              >
            </p>
          </div>
          {% endfor %}
        </div>

        <hr />
        {% block content %} {% endblock content %}
      </div>
      <!-- /container -->
    </main>

    {% include "footer.html" %}
    <!--  -->
    {% include "scripts.html" %}
  </body>
</html>

templates/craigslist/new_search.html
{% extends "base.html" %}
<!--  -->
{% block content %}
<h2 style="text-align: center">{{search}}</h2>
<hr />
<div class="container">
  <div class="row">
    {% for post in final_postings %}
    <div class="col-md-4">
      <img
        src="{{ post.3 }}"
        alt="..."
        style="max-width:480px; max-height:480px;"
      />
      <p>{{post.0}}</p>
      <p>
        <a
          class="btn btn-primary"
          href="{{post.1}}"
          role="button"
          target="_blank"
          >View details &raquo;</a
        >
      </p>
    </div>
    <hr />
    <br />
    {% endfor %}
  </div>
</div>
<br />
{% endblock content %}

templates/footer.html
<footer class="container">
  <p>&copy; Company 2017-2019</p>
</footer>

templates/head.html
{% load static %}

<head>
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  <meta name="description" content="" />
  <meta
    name="author"
    content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
  />
  <meta name="generator" content="Jekyll v3.8.6" />
  <title>Craiglist Template</title>

  <link
    rel="canonical"
    href="https://getbootstrap.com/docs/4.4/examples/jumbotron/"
  />

  <!-- Bootstrap core CSS -->
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />

  <meta name="theme-color" content="#563d7c" />

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{% static "css/style.css" %}" rel="stylesheet" />
</head>

templates/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarsExampleDefault"
    aria-controls="navbarsExampleDefault"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"
          >Disabled</a
        >
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle"
          href="#"
          id="dropdown01"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"
          >Dropdown</a
        >
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form
      action="{% url 'craig:new_search' %}"
      method="POST"
      class="form-inline my-2 my-lg-0"
    >
      {% csrf_token %}
      <input
        class="form-control mr-sm-2"
        type="text"
        name="search"
        placeholder="Search"
        aria-label="Search"
      />
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
        Search
      </button>
    </form>
  </div>
</nav>

templates/old_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "head.html" %}

  <body>
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="/">Home</a>
    </nav>
    <div class="container">
      <div class="row">
        {% for link in links %}

        <ul>
          <a href="{{link.0}}" target="_blank"><li>{{link.1}}</li></a>
        </ul>
        {% endfor %}
      </div>
      {% block content %} {% endblock content %}
    </div>

    {% include "scripts.html" %}
  </body>
</html>

templates/scripts.html
<script
  src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
  integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
  crossorigin="anonymous"
></script>